package com.company.recruitment_task.model.person.dto;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.company.recruitment_task.utils.PersonDeserializer;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonDeserialize(using = PersonDeserializer.class)
public class PersonDto {

    @Schema(description = "Internal id generated by postgres")
    private Long id;

    @Schema(description = "External id provided by the person provider api")
    private Long externalId;

    private String name;
    private Integer height;
    private Integer mass;
    private Boolean isTrue;

}